### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by immonomono** [mil-tokyo/bc_learning_sound#10]
Hello,

Can you let me know the test environment?

I've test with Ubuntu 18.04, chainer 1.24, Cuda 10.0 and cudnn 7.4.2.24
But the following problem occurred

+------------------------------+
| Sound classification
+------------------------------+
| dataset  : esc50
| netType  : envnet
| learning : standard
| augment  : False
| nEpochs  : 600
| LRInit   : 0.01
| schedule : [0.5, 0.75]
| warmup   : 0
| batchSize: 64
+------------------------------+
/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/chainer/cuda.py:92: UserWarning: cuDNN is not enabled.
Please reinstall chainer after you install cudnn
(see https://github.com/pfnet/chainer#installation).
  'cuDNN is not enabled.\n'
+-- Split 1 --+
Traceback (most recent call last):
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 49, in _run_nvcc
    return subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['nvcc', '--cubin', '-arch', 'sm_61', '/tmp/tmpj3ibf3vg/kern.cu']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 56, in <module>
    main()
  File "main.py", line 22, in main
    train(opt, split)
  File "main.py", line 42, in train
    train_loss, train_top1 = trainer.train(epoch)
  File "/home/mono/dev/voice/recognition/bc_learning_sound/train.py", line 30, in train
    y = self.model(x)
  File "/home/mono/dev/voice/recognition/bc_learning_sound/models/envnet.py", line 28, in __call__
    h = self.conv1(x, self.train)
  File "/home/mono/dev/voice/recognition/bc_learning_sound/models/convbnrelu.py", line 16, in __call__
    h = self.conv(x)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/chainer/links/connection/convolution_2d.py", line 109, in __call__
    deterministic=self.deterministic)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/chainer/functions/connection/convolution_2d.py", line 415, in convolution_2d
    return func(x, W)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/chainer/function.py", line 310, in forward
    return self.forward_gpu(inputs)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/chainer/functions/connection/convolution_2d.py", line 155, in forward_gpu
    cover_all=self.cover_all)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/chainer/utils/conv.py", line 74, in im2col_gpu
    h, w, out_h, out_w, kh, kw, sy, sx, ph, pw, dy, dx, col)
  File "cupy/core/elementwise.pxi", line 552, in cupy.core.core.ElementwiseKernel.__call__ (cupy/core/core.cpp:43113)
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1480)
  File "cupy/core/elementwise.pxi", line 409, in cupy.core.core._get_elementwise_kernel (cupy/core/core.cpp:41459)
  File "cupy/core/elementwise.pxi", line 12, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:34090)
  File "cupy/core/elementwise.pxi", line 32, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:33912)
  File "cupy/core/carray.pxi", line 86, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:33567)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 156, in compile_with_cache
    cubin = nvcc(source, options, arch)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 78, in nvcc
    _run_nvcc(cmd, root_dir)
  File "/home/mono/anaconda3/envs/pytorch/lib/python3.5/site-packages/cupy/cuda/compiler.py", line 56, in _run_nvcc
    raise RuntimeError(msg)
RuntimeError: `nvcc` command returns non-zero exit status. 
command: ['nvcc', '--cubin', '-arch', 'sm_61', '/tmp/tmpj3ibf3vg/kern.cu']
return-code: 1
stdout/stderr: 
b'/tmp/tmpj3ibf3vg/kern.cu(14): error: identifier "__float2half_rn" is undefined\n\n/tmp/tmpj3ibf3vg/kern.cu(17): error: identifier "__float2half_rn" is undefined\n\n/tmp/tmpj3ibf3vg/kern.cu(20): error: identifier "__float2half_rn" is undefined\n\n/tmp/tmpj3ibf3vg/kern.cu(23): error: identifier "__float2half_rn" is undefined\n\n/tmp/tmpj3ibf3vg/kern.cu(26): error: identifier "__float2half_rn" is undefined\n\n/tmp/tmpj3ibf3vg/kern.cu(29): error: identifier "__float2half_rn" is undefined\n\n/tmp/tmpj3ibf3vg/kern.cu(32): error: identifier "__float2half_rn" is undefined\n\n/tmp/tmpj3ibf3vg/kern.cu(35): error: identifier "__half2float" is undefined\n\n8 errors detected in the compilation of "/tmp/tmpxft_0000207a_00000000-6_kern.cpp1.ii".\n'

**Comment by q739554534** [comment]
My esc 10 result is 20%. How much does your result be?
